version: '3.7'
services:
    slosh:
        image: "slosh"
        build:
            context: ..
            dockerfile: docker/Dockerfile
        environment:
            DEBUG: "true"
        volumes:
            - ..:/app
        ports:
            - "80"

    slosh-proxy:
        image: nginx:alpine
        volumes:
            - type: bind
              source: ../config/nginx
              target: /etc/nginx/conf.d
        ports:
            - "${DEV_PORT}80"
        depends_on:
            - slosh
